version: "3"
services:
  redis:
    image: redis
    volumes:
      - ./redisd:/data
    expose:
      - "6379"
  wserv:
    build:
      context: ma
    expose:
      - "3000"
    depends_on:
      - redis
    restart: on-failure
    links:
      - redis
  wservb:
        build:
          context: ma
        expose:
          - "3000"
        depends_on:
          - redis
        restart: on-failure
        links:
          - redis
  wservc:
            build:
              context: ma
            expose:
              - "3000"
            depends_on:
              - redis
            restart: on-failure
            links:
              - redis
  hapro:
        build:
          context: haprox
        expose:
          - "80"
          - "70"
        depends_on: 
          - wserv
          - wservb
          - wservc
        links: 
          - wserv
          - wservb
          - wservc
        
  nginx:
    build:
      context: ngi
    ports: 
      - 80:80
    depends_on: 
      - hapro
    links: 
      - hapro
  